//! warp-audit runner: executes all 70 verification gates, writes
//! `verification_matrix.json` and exports LaTeX macros `warp_results.tex`.

use std::io::Write;

fn main() {
    let results = warp_audit::run_all();
    let passed = results.iter().filter(|r| r.passed).count();
    let total = results.len();

    // verification_matrix.json
    let json = serde_json::json!({
        "suite": "shbt-warp 70-gate verification",
        "gates": results,
        "passed": passed,
        "total": total,
    });
    let mut f = std::fs::File::create("verification_matrix.json")
        .expect("create verification_matrix.json");
    f.write_all(serde_json::to_string_pretty(&json).unwrap().as_bytes())
        .unwrap();

    // warp_results.tex LaTeX macros
    let mut tex = std::fs::File::create("warp_results.tex").expect("create warp_results.tex");
    writeln!(tex, "% Auto-generated by warp-audit — do not edit.").unwrap();
    writeln!(tex, "\\def\\WarpGatesPassed{{{}}}", passed).unwrap();
    writeln!(tex, "\\def\\WarpGatesTotal{{{}}}", total).unwrap();
    for r in &results {
        let macro_name = format!("\\def\\WarpGate{}{{{}}}", &r.gate[5..], if r.passed { "PASS" } else { "FAIL" });
        writeln!(tex, "{}", macro_name).unwrap();
    }

    for r in &results {
        println!(
            "{} {:<38} metric={:<12.3e} tol={:<12.3e} {}",
            r.gate,
            r.name,
            r.metric,
            r.tolerance,
            if r.passed { "PASS" } else { "FAIL" }
        );
    }
    println!("{}/{} gates passed", passed, total);
    if passed != total {
        std::process::exit(1);
    }
}
